### ISSUE TITLE
Disable pipeline collection on strings

### ISSUE THREAD

**Issue by avinabadasgupta** [sparcians/map#13]
Now that the core example and other examples use NVP for data collection, I want to remove ALL ability to collect data for pipeouts as strings. 
This means the following:
1. Remove Collection methods from all of Sparta’s resources. Modelers can now create explicit sparta::Collectable objects if they want them collected.
2. Move sparta::Collectable to look only for NVP registrations. Annotations will be allowed, but … barely. Need to figure that out.

**Comment by avinabadasgupta** [comment]
One idea I have is, keep the Collection class template for non pair collectable types, like ints, doubles etc. Within that, we can remove all the mechanism for string conversions, bypass all the pair collectable functions like looking for add pair, name-value arguments and just store the value as it is, in the binary record file. This can be done by introducing a new transaction_t type which is neither annotation nor pair. If we always store 8 bytes of space for this new transaction_t type, then writing and reading to/from the binary file can be faster but we would store extra for narrower POD types. That is the tradeoff.

**Comment by klingaard** [comment]
This will be revamped in #509
