### ISSUE TITLE
unable to create environment from rendered conda recipe on Ubuntu

### ISSUE THREAD

**Issue by MichaelSchoenfelder-SiV** [sparcians/map#145]
When executing `./scripts/create_conda_env.sh sparta dev` on Ubuntu 16, conda complains that it doesn't know how to merge X and Y for a variety of packages where the last `=id` differs between the packages.  If I remove all the conflicts by deleting one of the duplicates from the environment file, the script finishes.  However, the environment can't be created due to multiple unresolvable conflicts.  Only after removing the build id pins was I able to create the environment.

@timsnyder

**Comment by klingaard** [comment]
So, Mike, do you have a solution to push on this?

**Comment by MichaelSchoenfelder-SiV** [comment]
No.  @timsnyder is familiar with the problem and had already built some workarounds into the flow.  I am not sure why they didn't work.  It may be a problem in conda itself.  My solution at SiFive was to manually manipulate the recipe until it worked, but that isn't faithful to the intent of the solution.

**Comment by MichaelSchoenfelder-SiV** [comment]
Other conda maintenance: We also need to add the lld package to support LTO.  And it looks like we might be able to bump the LLVM to v11 since v11 is now available in conda forge.  I will be testing LLVM in a semi-manually-built conda environment.

**Comment by jackjchen** [comment]
@MichaelSchoenfelder-SiV , I ran into a similar issue on OSX 11.5.2. Changed some versions to get a rendered recipe, but the solver had numerous conflicts. Do you have a working environment yaml to share?
