### ISSUE TITLE
add a public API to sparta::SimulationConfiguration 

### ISSUE THREAD

**Issue by MichaelSchoenfelder-SiV** [sparcians/map#164]
As a simulator writer I want to access non-sparta configuration files specific to my simulator.  It would be helpful to look for those files on `--arch-search-dir`, but the simulator needs a way to ask sparta for that path information.

**Comment by klingaard** [comment]
Arch search dir is provided by the simulator writer to the `SimulationConfiguration` class via `sparta::app::DefaultValues` typically listed in the `main.cpp` file.  Technically, this issue is something that should be handled by the simulation writer, but I'll add the public APIs to be complete.
