### ISSUE TITLE
Sparta Collectable throws exception when collecting a nullptr pointer

### ISSUE THREAD

**Issue by davidsifive** [sparcians/map#166]
I have a Unit with these data members:
```
    using FooPtr = sparta::SpartaSharedPointer<Foo>;
    FooPtr foo_ptr_;
    sparta::collection::Collectable<FooPtr> foo_ptr_collector_;
```
If foo_ptr == nullptr, as it is most of the time in my use case, the Collectable throws an exception because it dereferences foo_ptr without checking whether it is a nullptr:

```
            //! Explicitly/manually collect a value for this collectable, ignoring
            //! what the Collectable is currently pointing to.
            //! Here we pass the shared pointer to the actual object of the collectable type we are collecting.
            template <typename T>
            MetaStruct::enable_if_t<MetaStruct::is_any_pointer<T>::value, void>
            collect(const T & val){
                collect_(*val);
                ...
```

**Comment by avinabadasgupta** [comment]
I think this was the intended behavior. This method ignores what the pointer is pointing to and attempts to collect.

**Comment by klingaard** [comment]
I dunno about that.  Shouldn’t it close the record if the pointer is now nullified?

**Comment by davidsifive** [comment]
Is that really the behavior we want?  I can collect a buffer or pipe of nullptr pointers, I think.  Why can't I collect a single nullptr pointer?

Regardless, this is not an immediate issue for me anymore.  For my use case it turns out I need to collect manually in tick.  To collect this I call
```
foo_ptr_collector_.collectWithDuration(1);
```
when ever I update foo_ptr_ with a valid pointer.
