### ISSUE TITLE
sparta::Buffer<sparta::SpartaSharedPointer<U>>::erase() should decrement refcount

### ISSUE THREAD

**Issue by kevin-heuer** [sparcians/map#169]
`sparta::Buffer<sparta::SpartaSharedPointer<U>>::erase()` doesn't decrement the refcount of the `sparta::SpartaSharedPointer<U>` being erased (because `sparta::Buffer<T>` code is rightfully generic and has no idea `T == sparta::SpartaSharedPointer<U>` for `sparta::Buffer<sparta::SpartaSharedPointer<U>>` instances), **which may cause `U` instances to hang around longer than expected**.

Users can work around this by using `*itr = nullptr;` right before `erase(itr);`, but it would be best to handle this automatically in `sparta::Buffer` with template specialization or whatever makes the most sense.

E.g. change `erase()` to `eraseImpl_()`; `sparta::Buffer<T>::erase()` will only call `eraseImpl_()`; `sparta::Buffer<sparta::SpartaSharedPointer<U>>::erase()` will execute `*itr = nullptr;` before calling `eraseImpl_()`.

I haven't been able to get this specific template specialization to work, but this is the general idea.

**Comment by knute-sifive** [comment]
So I've added support for this in branch knutel/issue_169_buffer_erase but SiFive simulations are not happy with it.
