### ISSUE TITLE
Sparta's memory allocator allows modeler's to shoot foot

### ISSUE THREAD

**Issue by knute-sifive** [sparcians/map#17]
Currently the `SpartaSharedPointerAllocator` will complain if it's being deleted and there are outstanding `SpartaShared` pointers hanging out in simulation.  This is good, but bad. Two things happen:

1. The outstanding memory objects are now orphaned.
1. The outstanding memory objects memory is deleted (i.e. they're gutted!)

Need to figure out a better mechanism to handle this problem.

**Comment by klingaard** [comment]
After thinking about this for a bit, I had a "der" moment.  Pool allocators are static for a reason -- this Issue's reason.  Technically the pool allocator should be the last thing destructed in a program -- this guarantees all memory has either been returned (in a well-behaved program) or at least will no longer be accessed by a bad one.  This allocator is no different.  I will update the comments on expected and suggested uses for the allocator.
