### ISSUE TITLE
Hierarchical block boundary interfacing

### ISSUE THREAD

**Issue by nilanjan** [sparcians/map#172]
Hierarchical block boundary crossing requires additional ports and manual driving. 

For example a super-block "S" has two sub-blocks "SA" and "SB". Another super-block "X" interfaces one data port to S and another credit port back from S to X. 

X->S (data)
S->X(credit)

The super-block just forward the data to say one sub-block "A".  Similarly, return the credit from SA to S to X.

X->S-->SA (data)
SA-->S->X (credit)

S each tick forward the data from X to SA and from SA to X. S interfaces are just used forwarding. 

I think systemC had something like sc_export. I was wondering if there is something like this already exists in SPARTA that I am aware of which helps automatic boundary crossing?

**Comment by knute-sifive** [comment]
I've received this request from a couple of folks using Sparta (coming from SysC).  Sparta, of course, is by no means a replacement for SysC, but Sparta does lack a few convenience features like "pass through" or exporting of internal ports.  It was never added for the simple reason that it was never a requirement.

Anyway, it's not a bad feature to add.  Right now (using your example), the user is required to know the hierarchy to perform the binding of an internal port to a component _outside_ of the "super-block."

So it would look like this (using Sparta):
```
std::bind("X.a.b.c.ports.out_send_data", "S.f.g.h.in_receive_data");
```
What you want:
```
std::bind("X.ports.out_send_data", "S.ports.in_receive_data");
```
where `out_send_data` is actually an alias to `a.b.c.ports.out_send_data` and `in_receive_data` is actually an alias to `f.g.h.in_receive_data`

**Comment by nilanjan** [comment]
Thanks @klingaard for your response. 
This feature would be great for many. 

Alternatively, several ports (outside to boundary, boundary to inside block, etc.) are auto-generated or manually written for boundary crossing scenario in the topology file. Or as you mentioned, directly connecting to inside block is also possible then the purpose of hierarchy is void.

**Comment by klingaard** [comment]
I've added an initial implementation of the ExportedPort in PR https://github.com/sparcians/map/pull/300.  Have a look and provide feedback if you have the time!
