### ISSUE TITLE
Log option argument missing error

### ISSUE THREAD

**Issue by nilanjan** [sparcians/map#173]
The "--log" DEST parameter can be "1" to refer to stdout, "2" to refer to stderr, or a filename which can contain any extension shown. 
This is mentioned in the help message. I haven't done any initialization related stuff for the loggers but using `info_logger_` and `warn_logger_` various places. If I run the binary using `--log 1` it reports error like:
```
Error:
  the required argument for option '--log' is missing
```
If run with `--log run_info.log.verbose` this I get exact same error.

**Comment by nilanjan** [comment]
I found the solution to this. Log can be turned on like this:

`--log top.path.to.node '*' 1`                          ----> STDOUT
`--log top.path.to.node '*' file.log.verbose`  ----> To a file

Details in `CommandLineSimulator.cpp`:

        ("log,l",
         named_value<std::vector<std::vector<std::string>>>("PATTERN CATEGORY DEST", 3, 3)->multitoken(),
         "Specify a node in the simulator device tree at the node described by PATTERN (or nodes "
         "using '*' and '?' glob wildcards) on which to place place a log-message tap (observer) "
         "that watches for messages having the category CATEGORY. Matching messages from those "
         "node's subtree are written to the filename in DEST. DEST may also be '1' to refer to "
         "stdout and '2' to refer to cerr. Any number of taps can be added anywhere in the device "
         "tree. An error is generated if PATTERN does not refer to a 1 or more nodes. Use "
         "--help for more details\n"
         "Example: \"--log top.core0 warning core0_warnings.log\"",
         "Example: \"--log top.core0 '*' core0_all.log\"",
         "Attaches logging tap(s) at nodes matching a location pattern. Directs output matching "
         "category to destination")

**Comment by klingaard** [comment]
Correct.  As the help message indicates, there are three required parameters: `-l [ --log ] PATTERN CATEGORY DES`

Where `CATEGORY` is directly related to the name of the logger (`sparta::log::MessageSource`) instantiated.  If a modeler derives from `sparta::Unit` you will get three loggers by default (category: "info", "debug", and "warning"). 

The logger option can be supplied multiple times, with each instance referring to either a separate destination or the same destination.  The framework is smart enough to merge loggers together.  See the [Skeleton Pipeline](https://sparcians.github.io/map/skeleton_example.html) section "Running the simulator and generating logs" for examples.

You can always get more/detailed information on a topic:
```
./sparta_core_example --help-topic logging
```
