### ISSUE TITLE
No documentation on the visualization tools

### ISSUE THREAD

**Issue by borja-perez** [sparcians/map#183]
Currently there is no documentation on the visualization tools of map. At least some information on where to start would be very helpful for newbies.

**Comment by knute-sifive** [comment]
Couple of things we're going to do:
- [] Update the CoreModel and the Skeleton Pipeline doxygen documentation to show how to generate a pipeout
- [] Update the pipeView repo README.md with documentation on how to build
- [] Update the `gen_alf` tools and documentation
- [] Add to sparcians.github.io links

**Comment by knute-sifive** [comment]
I've pushed some updates to the CoreModel documentation to generate a Pipeout (branch  knute/issue_183_pipeView_docs).  Top is working on documenting the tools to create the ALF files used by Argos.

**Comment by knute-sifive** [comment]
Top has a few branches under review that should be merged today.  I have some updates to follow as well.

**Comment by borja-perez** [comment]
That is great. I will check it out. Thank you very much.

**Comment by knute-sifive** [comment]
It might take a few hours for the Doxygen to be available, but the README.md documentation has been updated to provide guidance and it available now:

https://github.com/sparcians/map/tree/master/helios/pipeViewer

eventually the doxygen will be updated with more information on how run the simulator as well:

https://sparcians.github.io/map/core_example.html
