### ISSUE TITLE
Add SystemC adapter test/example

### ISSUE THREAD

**Issue by klingaard** [sparcians/map#197]

**Comment by klingaard** [comment]
One exists in `sparta/test/SystemC` but it's not active yet.

**Comment by knute-sifive** [comment]
This work is done, but can be extended over time.

**Comment by vikramkapoor** [comment]
Let me know if I can be of help in adding anything.
Vikram
    On Tuesday, November 3, 2020, 12:29:02 PM PST, Knute Lingaard <notifications@github.com> wrote:  
 
 


This work is done, but can be extended over time.

**Comment by klingaard** [comment]
Thanks, Vikram, appreciate it.
