### ISSUE TITLE
Build error on mac

### ISSUE THREAD

**Issue by vikramkapoor** [sparcians/map#199]
[ 80%] Built target sparta
[ 88%] Built target simdb
[ 88%] Generating build/core.so.built
Using CYTHON: ['/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/Cython'] : 0.29.21
None
Traceback (most recent call last):
  File "/Users/vkapoor/map/helios/pipeViewer/pipe_view/core/setup.py", line 29, in <module>
    inc_dirs = [os.path.join(os.path.dirname(wx_pkg.get_filename()), 'include')]
AttributeError: 'NoneType' object has no attribute 'get_filename'
make[2]: *** [helios/pipeViewer/build/core.so.built] Error 1
make[1]: *** [helios/pipeViewer/CMakeFiles/pipe_view_py.dir/all] Error 2
make: *** [all] Error 2

**Comment by knute-sifive** [comment]
Did you do this using the miniconda environment? 

https://github.com/sparcians/map/tree/master/helios/pipeViewer

**Comment by vikramkapoor** [comment]
I believe I did. Its been a few weeks. I will retry it when I get some time.

**Comment by knute-sifive** [comment]
Gonna assume this is working now...  Please reopen if not.
