### ISSUE TITLE
Issue when compiling the PipeViewer

### ISSUE THREAD

**Issue by borja-perez** [sparcians/map#204]
I have followed the instructions in the readme to build the pipeViewer and encountered a linking error when making. The error is as follows:

```
/home/bscuser/miniconda3/envs/sparta/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: ../../../sparta/libsparta.a(Scheduler.cpp.o): undefined reference to symbol 'clock_gettime@@GLIBC_2.2.5'
/home/bscuser/miniconda3/envs/sparta/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/bscuser/miniconda3/envs/sparta/bin/../x86_64-conda-linux-gnu/sysroot/lib64/librt.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [helios/pipeViewer/argos_dumper/CMakeFiles/Argos_dumper.dir/build.make:114: helios/pipeViewer/argos_dumper/Argos_dumper] Error 1
make[1]: *** [CMakeFiles/Makefile2:5418: helios/pipeViewer/argos_dumper/CMakeFiles/Argos_dumper.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```

Basically, the linking failed for _clock_gettime_. I think that this is related to my linker always getting passed the _-Wl, --as-needed_ flags. I have fixed this and successfully completed compilation/linking by adding _-lrt_ to the _target_link_libraries_ in _map/helios/pipeViewer/argos_dumper/CMakeLists.txt_

**Comment by knute-sifive** [comment]
Hey Brett, got an ideas on how to make this robust?

**Comment by bdutro** [comment]
> adding -lrt to the target_link_libraries in map/helios/pipeViewer/argos_dumper/CMakeLists.txt

This will probably take care of it. I wonder why we haven't seen this in any other environments though.

**Comment by knute-sifive** [comment]
Do you mind making a PR for this?

**Comment by knute-sifive** [comment]
Completely forgot that Tim addressed this.

**Comment by knute-sifive** [comment]
Borja, please reopen if still an issue.
