### ISSUE TITLE
A bool param should not allow specifying a string

### ISSUE THREAD

**Issue by TopChangwatchaiSiFive** [sparcians/map#214]
@davidsifive discovered that if you have a `bool` parameter and you specify a default value of the character string `"false"` then this gets auto converted into a `true` boolean value.

Is there a good way to stop this silent bug?

**Comment by knute-sifive** [comment]
Example:
```
PARAMETER(bool, my_boolean, "false", "A false string boolean that's actually true?")
```

**Comment by knute-sifive** [comment]
Unfortunately, this is really hard to catch.  The `Parameter` class is created as a `bool` type, but the language allows the user to supply a `char *` as a possible value.  If the pointer `!= nullptr` then it's `true`.  I.e. `("false" != nullptr) == true`

**Comment by knute-sifive** [comment]
I've tried a few tricks, but it's a LOT of code to catch a silly mistake.  I think this isn't worth fixing or attempting to catch.
