### ISSUE TITLE
Please list MAP's benefits/detriments to SystemC like libraries in the ReadMe file

### ISSUE THREAD

**Issue by nilanjan** [sparcians/map#216]
It would be great convincing people using MAP over systemC if the ReadMe file list bunch of benefits of MAP over SystemC like platform. That may list performance, interfacing, usage, statistics calculation, additional feature benefits.

**Comment by klingaard** [comment]
Not sure I want to convince folks to use Sparta over SysC, but rather show folks how to use Sparta who are coming from a SystemC background.  There are benefits and detriments to both frameworks, so I can work on that list.  I'll need help from someone more familiar with SystemC than I to have a comprehensive list.

**Comment by nilanjan** [comment]
@klingaard Thanks for your response. I think comparison will be even more beneficial.

**Comment by klingaard** [comment]
I moved this to a discussion: https://github.com/sparcians/map/discussions/299
