### ISSUE TITLE
Dumping interface transaction data

### ISSUE THREAD

**Issue by nilanjan** [sparcians/map#219]
Hi All:

Are there any mechanism in Sparta to dump interface transaction vectors as text files? Or users need to implement one? 

Thanks,
Nilanjan

**Comment by klingaard** [comment]
An unsatisfactory response, but one that gets you going without the need for making source code changes:

The framework supports dumping the transactions between an `OutPort` and an `InPort` type (`Port` types) via the [`PipelineCollector`](https://sparcians.github.io/map/classsparta_1_1collection_1_1PipelineCollector.html).  Under the covers the ports use a [`Collectable`](https://sparcians.github.io/map/classsparta_1_1collection_1_1Collectable.html) to collect the port data during the [`Collection` phase](https://sparcians.github.io/map/namespacesparta.html#aeec80d237ace9f07634c3d24c9aed9a0) (right after the port is updated/ready with new data).  You _must_ enable collection on the port to get that data included in the pipeout via [`Port::enableCollection(parent_tn)`](https://sparcians.github.io/map/classsparta_1_1Port.html#aa5cfbb76627462d2b4e33b4c44759e24).

When the simulator is setup to collect data, generate a pipeout: 
```
# Generate a pipeout for everything
./my_simulator -z pipeout

# Generate a pipeout for just a few ports
./my_simulator -z pipeout -k top.<my unit1>.ports -k top.<my unit2>.ports
```

Once you collect the data, you can use this tool to convert it from a binary to a text file:
```
~/sparcians/map/release/helios/pipeViewer/argos_dumper/DatabaseDump/ArgosDumper pipeout
```

You can write your own collector, but time wise, it can be expensive if it lives outside the Port.  Currently ports are collected _when they change_, but if you write your own collector, you'll have to poll the port for new data every cycle.   I'd like to change the Port to take a user-defined collector in the future, but that'll take some template magic...

To write your own collector efficiently, I'd do the following:

- To Port.hpp, add a method `getConsumerHandler()` that returns the undelying `explicit_consumer_handler_` be reference (you'll see why in a minute)
- Create a class that derives from TreeNode with some methods like:
  ```
  class PortCollector : public sparta::TreeNode
  {
  private:
      // For DataPorts
      template<class DataT>
      void collectPortData_(const DataT & dat)
      {
           my_ostream_ << dat << std::endl;
           registered_consumer_handler_((const void *)&dat);
      }
      sparta::SpartaHandler registered_consumer_handler_;
  public:
      // Construct this tree node with a file in which all port data is written
      PortCollector(sparta::TreeNode *parent, const std::string & port_data_file) : 
          sparta::TreeNode("port_collector", ,,,) {}

      // For DataPorts
      template<class DataT>
      void registerPortForCollection(const sparta::DataInPort<DataT> & port)
      {
           registered_consumer_handler_ = port.getConsumerHandler();
           port.registerConsumerHandler(CREATE_SPARTA_HANDLER_WTH_DATA(PortCollector, collectPortData_<DataT>, DataT));
      }
  };
  ```
- In your top-level Simulator class, add this `PortCollector` class to the tree, preferrable at the root level:
    ```
    to_delete_.emplace_back(new PortCollector(getRoot(), "port_data_outfile.txt");
    ```
- For each class that has a port to collect:
  ```
    class MyUnit
    {
    public:
        MyUnit(sparta::TreeNode * node, const MyUnitParameters * params) : ...
             my_data_in_port_(getPortSet(), "my_data_in_port")
        {
            // MUST DO THIS FIRST
            my_data_in_port_.registerConsumerHandler
                (CREATE_SPARTA_HANDLER_WITH_DATA(MyUnit, my_handler_, data_type));
            if(params->collect_port_data) {
                // The following line will "throw" if not found
                auto port_collector = getRoot()->getChild("port_collector")->getResourceAs<PortCollector>();
                port_collector.registerPortForCollection(my_data_in_port_);
            }
        }
     };
    ```

This should get you there.  Forgive me if the code has a few errors in it.  :wink:

**Comment by nilanjan** [comment]
@klingaard  Thanks a lot for your detailed response.

**Comment by klingaard** [comment]
Let me know if you want anymore help...
