### ISSUE TITLE
sparta::Queue performance improvements

### ISSUE THREAD

**Issue by eabsi5** [sparcians/map#22]
sparta::Queue uses new[] (queue_data_.reset(new value_type[vector_size_]);). It would be nice to take an allocator parameter, and add an rvalue ref version of push to reduce copying.

**Comment by klingaard** [comment]
Totally agree on the rvalue ref.  I was looking into that for the resources as well as the ports.  It's gets nasty fast, however.

The allocator -- meh.  Typically the Queue is created at the beginning of simulation and this memory is allocated once.  Not sure what the allocation would buy you...

**Comment by avinabadasgupta** [comment]
I agree. Every push back, push front kind of methods must accept both lvalue and rvalue references, depending on how users pass the arguments. C++ has this handy perfect forwarding feature that we can use here.

**Comment by avinabadasgupta** [comment]
Ran into problems regarding this issue. I wanted to have a queue of unique pointers. But I could not push into the queue as the push API does a copy internally. We need to make the push API accept universal reference of value_type and move into the internal container to make unique pointers work.
