### ISSUE TITLE
sparta::QueueIterator -> operator incorrect?

### ISSUE THREAD

**Issue by TopChangwatchaiSiFive** [sparcians/map#23]
Queue.hpp has:

    /// Dereferencing operator
    DataReferenceType operator* ()
    {
        sparta_assert(getIndex()<attatched_queue_->total_valid_, "Not a valid Iterator");
        return getAccess_(std::integral_constant<bool, is_const_iterator>());
    }

    ///support -> operator
    DataReferenceType operator->()
    {
        return operator*();
    }

Should `operator->` return a pointer type?

**Comment by avinabadasgupta** [comment]
You're right. The dereference op. is broken and not just in Queue, but also in CircularBuffer and Array or Buffer. I had identified and fixed it long time ago but there were breaking changes w.r.t. Fiat and so, was never pushed to production. I could fix it again, if you want.

**Comment by klingaard** [comment]
YES!  Please do.  If you can do it tonight (and add testing) we'd appreciate it!

**Comment by avinabadasgupta** [comment]
Sure.
