### ISSUE TITLE
In Argos change font size of tooltips

### ISSUE THREAD

**Issue by TopChangwatchaiSiFive** [sparcians/map#234]
@benoy-sifive reported this.  On his Mac, the tooltips font is too small.

The main Argos window can be resized using `Ctrl`+scroll (`Cmd`+scroll on Mac), or using `Ctrl` + Plus, Minus, or Zero keys.

However, this doesn't change the font size of tooltips.

Currently, the tooltip font size is set here:  https://github.com/sparcians/map/blob/4026a37409f95761df34d6140c47630478bc09d0/helios/pipeViewer/pipe_view/gui/hover_preview.py#L46

Two possible solutions:
1. Add persistent settings that users can set
2. Tooltip should zoom in/out the same as the main Argos window (not sure how this would be done)

**Comment by bdutro** [comment]
@TopChangwatchaiSiFive I'm about 90% of the way to a working solution for this.
