### ISSUE TITLE
Request Scheduler to provide system/wall clock run time

### ISSUE THREAD

**Issue by knute-sifive** [sparcians/map#251]
Simulation performance is currently measured in user seconds, which doesn't provide too much useful information regarding the rest of the simulation -- is there time lost in the system? 
```
Elapsed:  264.418s
  Simulation Performance: 28.3509 KTPS (1k ticks per second)
  Scheduler Event Rate:   1025.91 KEPS (1k events per second)
  Scheduler Events Fired: 268479791
manual calculation: 268479.791 * 1/1025.91 = 261.70 seconds
```

**Comment by MichaelSchoenfelder-SiV** [comment]
I am looking for wall, user and system elapsed times in two places:

1) printSchedulerPerformanceInfo()
2) wall_runtime_seconds to scheduler performance stats, as in

`Report "@ on _SPARTA_global_node_" [0,7419433]
  Report "scheduler"
      ticks = 7419432
      picoseconds = 7419432
      seconds = 7.41943e-06
      milliseconds = 0.00741943
      microseconds = 7.41943
      nanoseconds = 7419.43
      user_runtime_seconds = 155
      system_runtime_seconds = 0`

**Comment by knute-sifive** [comment]
New output:
```
Running Complete
  Simulation Performace      : wall(1.8522), system(0.0200), user(1.8300)
  Scheduler Tick Rate  (KTPS): 32.0251  (1k ticks per second)
  Scheduler Event Rate (KEPS): 1977.77 KEPS (1k events per second)
  Scheduler Events Fired: 3619326
```
New report counters and statistic defs/scheduler instance:
```
Report "@ on _SPARTA_global_node_" [0,58606]
  Report "scheduler"
      ticks = 58605
      picoseconds = 58605
      seconds = 5.8605e-08
      milliseconds = 5.8605e-05
      microseconds = 0.058605
      nanoseconds = 58.605
      host_machine_user_runtime_seconds = 1.81
      host_machine_system_runtime_seconds = 0.01
      host_machine_wall_runtime_seconds = 1.829
      host_user_time_count_ms = 1810
      host_system_time_count_ms = 10
      host_wall_time_count_ms = 1829
```
