### ISSUE TITLE
Argos ignores the IOS formatting specificed in the DB

### ISSUE THREAD

**Issue by klingaard** [sparcians/map#277]
Hello,  
I created my own PairDefinition to be used by the Helios pipeline viewer, and I followed the same example as in ExampleInst.hpp (ExampleInstPairDef).  

I am trying to display my addresses in hex instead of decimal, but even after using std::ios::hex I am unable to do this - it always comes out as decimal in the Helios pipeviewer tool.

Is this a known bug?  Has this been fixed?   
Thanks!

_Originally posted by @quasiquote1 in https://github.com/sparcians/map/discussions/274_

**Comment by knute-sifive** [comment]
Hey @bdutro-sv do you want to try to tackle this one?  It'd be real handy to get this working.  Also, a bunch of us would be grateful.  😄
