### ISSUE TITLE
argos does not adjust scrollbars when font size changes

### ISSUE THREAD

**Issue by BrianGraysonSiV** [sparcians/map#283]
Pull up a view of Argos. Then use the "View -> Settings" to make the font much bigger. Note that one cannot scroll to the bottom anymore.

It looks like the scrollbar/thumbbar is not resized after a font change.

**Comment by BrianGraysonSiV** [comment]
Looks great! One other thing I can suggest is, on the Settings... box, when it pops up the dialog box can you provide the help text of Ctrl+, Ctrl-, Ctrl0, and Ctrl-scrollwheel?

Also, I thought there used to be a menu option to show all the key bindings, but I don't see that anywhere, either under View or under Help.

One other random thing: "Hover Preview options" looks like there's something wrong with the font/rendering there -- Annotation is partially underneath Clock.

**Comment by bdutro** [comment]
@BrianGraysonSiV I just pushed a fix for the tiny help window to the `issue-283` branch.

**Comment by BrianGraysonSiV** [comment]
Can this be merged to master and all that?
