### ISSUE TITLE
DynamicModelPipeline vs CoreModel examples: what's the difference?

### ISSUE THREAD

**Issue by peter-d** [sparcians/map#291]
Hi

I have a example & documentation question: in the examples, there's `DynamicModelPipeline ` and  `CoreModel`, which seem largely but not fully the same. The documentation (which is excellent btw) lists only CoreModel as an example.

I had a look at the source code being new to the framework, it's hard to tell what exactly is the difference, Looks like the CoreModel has a better implementation of storing everything in the simdb (and hence also links up nicely with PipeViewer).

Thank you!
-Peter

**Comment by klingaard** [comment]
Hi Peter, do you mind opening a [discussion](https://github.com/sparcians/map/discussions) about this?  I'll be happy to respond in full there.  But in the meantime, you are correct, the difference between the two examples is ... well, nil.  The purpose of the `DynamicModelPipeline` was to be an illustration of how to use the python shell.  When @avinabadasgupta decides he wants to come back to do more cool stuff.  :wink:

**Comment by klingaard** [comment]
I'll need to document this model's original purpose or just squish it for now...
