### ISSUE TITLE
Memory_test.cpp fails regress target with compiler warning as error

### ISSUE THREAD

**Issue by jackjchen** [sparcians/map#3]
Using the map-docker devel-env image based on fedora 31 (latest) (gcc (GCC) 9.2.1), the following warning fails the regress target. This is the only warning when removing "-Werror" from cmake.
cc: @bdutro @bdutro-sv 

Scanning dependencies of target Memory_test
[ 51%] Building CXX object test/Memory/CMakeFiles/Memory_test.dir/Memory_test.cpp.o
In file included from /work/map/sparta/./sparta/simulation/ResourceTreeNode.hpp:9,
                 from /work/map/sparta/./sparta/sparta.hpp:17,
                 from /work/map/sparta/test/Memory/Memory_test.cpp:7:
/work/map/sparta/./sparta/functional/ArchData.hpp: In function ‘void testMemoryObjectPerformance()’:
/work/map/sparta/./sparta/functional/ArchData.hpp:381:23: error: ‘buf’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  381 |                 memcpy(data_ + offset, data, size);
      |                 ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/work/map/sparta/./sparta/functional/ArchData.hpp:381:23: error: ‘buf’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  381 |                 memcpy(data_ + offset, data, size);
      |                 ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/work/map/sparta/./sparta/functional/ArchData.hpp:381:23: error: ‘buf’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  381 |                 memcpy(data_ + offset, data, size);
      |                 ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/work/map/sparta/./sparta/functional/ArchData.hpp:381:23: error: ‘buf’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  381 |                 memcpy(data_ + offset, data, size);
      |                 ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[3]: *** [test/Memory/CMakeFiles/Memory_test.dir/build.make:63: test/Memory/CMakeFiles/Memory_test.dir/Memory_test.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:3725: test/Memory/CMakeFiles/Memory_test.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:2579: test/CMakeFiles/regress.dir/rule] Error 2
make: *** [Makefile:274: regress] Error 2

**Comment by klingaard** [comment]
Odd.  There is no `buf` at that line nor is there a `buf` in this function...

**Comment by klingaard** [comment]
There is, however, a `buf` in the tester does look uninitialized, even though it doesn't matter.  Can you try a patch for me?  I'm not seeing that warning with my gcc 9.2.
```
diff --git a/sparta/test/Memory/Memory_test.cpp b/sparta/test/Memory/Memory_test.cpp
index 5f8ca7f..151330b 100644
--- a/sparta/test/Memory/Memory_test.cpp
+++ b/sparta/test/Memory/Memory_test.cpp
@@ -4,6 +4,8 @@
 
 #include <boost/timer/timer.hpp>
 
+#include <cstring>
+
 #include "sparta/sparta.hpp"
 #include "sparta/simulation/TreeNode.hpp"
 #include "sparta/memory/BlockingMemoryIF.hpp"
@@ -606,6 +608,7 @@ void testMemoryObjectPerformance() {
 
     uint8_t dat[block_size];
     uint8_t buf[block_size];
+    memset((void*)buf, 0, sizeof(decltype(buf)));
 
     // General
     EXPECT_EQUAL(mem.getSize(), mem_size);
```

**Comment by jackjchen** [comment]
Thanks, that worked, maybe some additional warning code was added to gcc 9.2.1.

[100%]` tests passed, 0 tests failed out of 101

Total Test time (real) = 105.92 sec
[100%] Built target regress

**Comment by klingaard** [comment]
Great!  I'll test and push the code today.

**Comment by klingaard** [comment]
Pushed to master
