### ISSUE TITLE
Add a method to ParameterBase to check if the parameter has been set

### ISSUE THREAD

**Issue by kathlenehurt-sifive** [sparcians/map#313]
I need a method to check that a user has set a parameter. It is not enough to check that the parameter value is different than the default value, because in my use case all of the values of of this parameter could be valid.

**Comment by knute-sifive** [comment]
Hmmmm... does this method not work?  https://sparcians.github.io/map/classsparta_1_1ParameterBase.html#ae297438f7452736fc86dc6df8a477925

**Comment by kathlenehurt-sifive** [comment]
That method only works if the user sets the parameter to a different value than the default value. In my use case, the parameter type is a `uint64_t` and there isn't a default value that makes sense. What I really want is the `ValidValue` functionality for a parameter.

**Comment by klingaard** [comment]
Gonna poke at this one some more...  How about the method `isDefaultOverriden`?  https://sparcians.github.io/map/classsparta_1_1ParameterBase.html#a70c49466ee9754366c936f62b0154818

This will return `false` if the original value (in your case, the one that doesn't make sense) has not been changed.

**Comment by kathlenehurt-sifive** [comment]
Oh this is exactly what I need! Thanks!
