### ISSUE TITLE
Argos failed to import module: "transactiondb"

### ISSUE THREAD

**Issue by TopChangwatchaiSiFive** [sparcians/map#325]
This started showing up with PR #324 .

This used to work:
```
$ python <PATH>/helios/pipeViewer/pipe_view/argos.py ...
```
but now we get this error:
```
ERROR:root:Argos failed to import module: "transactiondb"
ERROR:root:The search paths (sys.path) were: <...>
ERROR:root:Please export the environment variable TRANSACTIONDB_MODULE_DIR to contain the absolute path of the directory wherein the SPARTA transactiondb module can be found. Currently is "{added_path}"
```

**Comment by TopChangwatchaiSiFive** [comment]
@bdutro mentioned:
> I think https://github.com/sparcians/map/pull/324 introduced a sqlite3 dependency into libsparta.a
and
> It looks like the only thing transactiondb actually needs to link against in libsparta is SpartaException. It might make sense to just stop using SpartaException in transactiondb so we don't have to worry about linking against libsparta at all.

**Comment by knute-sifive** [comment]
Yeah, the refactoring added some undefined symbols in the headers used by the transaction libraries.  Grumble.  

I think the best action is to have these libraries link against sparta and simdb.  It's too much of a web to untangle.
