### ISSUE TITLE
How to build Helios,  python 3.6 or python 3.8?

### ISSUE THREAD

**Issue by cyberspicecai** [sparcians/map#341]
Hi, Knute and all,
     I have find a strange issue: when i use Helios pipeview to visualize the sparta output, the pipeview will crash and report me Segmentation fault. 
        [root@intel6148 CoreModel]# python3 ~/map_Modeling_Architectural_Platform/helios/pipeViewer/pipe_view/argos.py -l cpu_layout.alf -d my_pipeout
        transaction search initialized: you will be able to use search.
        Using: /root/map_Modeling_Architectural_Platform/release/helios/pipeViewer/transactionsearch/transactionsearch
         Open the Database!!
        Launch Layout Frames
        INFO:root:Constructing layout "cpu_layout.alf"
        Constructing layout "cpu_layout.alf"
        INFO:root:Layout loaded with 112 elements in 0.11413431167602539s
        Layout loaded with 112 elements in 0.11413431167602539s
        Run the mainloop
        Segmentation fault
      
        I debug the core dumpfile. and the fault will is from
**(gdb) py-bt**
Traceback (most recent call first):
  File "/home/xrdpuser/map_Modeling_Architectural_Platform/helios/pipeViewer/pipe_view/gui/layout_canvas.py", line 213, in DoDraw
    self.__renderer.drawElements(dc, self, self.__context.GetHC())
  File "/home/xrdpuser/map_Modeling_Architectural_Platform/helios/pipeViewer/pipe_view/gui/layout_canvas.py", line 272, in OnPaint
    self.DoDraw(dc)
  <built-in function MainLoop>
  File "/usr/local/lib64/python3.8/site-packages/wx/core.py", line 2237, in MainLoop
    rv = wx.PyApp.MainLoop(self)
  File "/home/xrdpuser/map_Modeling_Architectural_Platform/helios/pipeViewer/pipe_view/argos.py", line 5449, in <module>
      OR:
**(gdb) bt**
#0  0x00007fffe77dd89d in wxGraphicsContext::SetFont(wxFont const&, wxColour const&) () at /usr/local/lib64/python3.8/site-packages/wx/libwx_gtk3u_core-3.1.so.5
#1  0x00007fffe778c44e in wxGCDCImpl::DoGetTextExtent(wxString const&, int*, int*, int*, int*, wxFont const*) const ()
    at /usr/local/lib64/python3.8/site-packages/wx/libwx_gtk3u_core-3.1.so.5
#2  0x00007fff901b11d2 in wxDC::SetClippingRegion(int, int, int, int) (this=0x555556dc6440, height=60, width=260, y=20, x=420) at /usr/include/wx-3.0/wx/dc.h:978
#3  0x00007fff901b11d2 in __pyx_pf_4core_8Renderer_24drawElements(__pyx_obj_4core_Renderer*, PyObject*, PyObject*, PyObject*)

       **My server info as following:**
       1, Intel 6148 CPU, 
       2, OS Rocky Linux release 8.6 (Green Obsidian) (and I try Ubuntu 20.04 LTS, the error  is the same as the above.

      What I compile Helios:
         1, conda (https://docs.conda.io/en/latest/miniconda.html) doesnot work.  the error is : _[root@intel6148 release]# conda install -c conda-forge jq
  ERROR: The install method you used for conda--probably either `pip install conda`
  or `easy_install conda`--is not compatible with using conda as an application.
  If your intention is to install conda as a standalone application, currently
  supported install methods include the Anaconda installer and the miniconda
  installer.  You can download the miniconda installer from
  https://conda.io/miniconda.html._
But I confirm: yq and jq are ok . 
  
[root@intel6148 release]# yq --version
yq 2.14.0
[root@intel6148 release]# jq --version
jq-1.6
       2, I remove the python3.6 and install python 3.8, otherwise the cmake will fail and ti says it needs at least  python 3.7.
       3, I  intall the wxpython and cpython, matplotlib, wx and so son.
       4, I chech the wx and matplotlib irrespectively, both are OK.

     Pls help debug or give a reference guide.

     Thanks a lot.

      Cyberspice

**Comment by bdutro-sv** [comment]
Can you give the output of the following commands:
```
wx-config --version
```

```
python -c 'import wx; print(wx.__version__)'
```

**Comment by cyberspicecai** [comment]
> Can you give the output of the following commands:
> 
> ```
> wx-config --version
> ```
> 
> ```
> python -c 'import wx; print(wx.__version__)'
> ```

[root@intel6148 release]# wx-config --version
3.0.4
[root@intel6148 release]# python -c 'import wx; print(wx.__version__)'
4.1.1

**Comment by cyberspicecai** [comment]
After existing issues check, I thinks the bug is related to wxpython 4.1.0.  And I uninstall wxpython 4.1.0 and install 4.0.7 and the pipviewer works.

**Comment by klingaard** [comment]
Hi @cyberspicecai, sorry for the delay -- day job's been keeping us busy.

Glad you figured out the issue.  The conda environment that we set up uses v4.0.7 and that does seem to work (as you figured out).

**Comment by knute-sifive** [comment]
I think this was addressed...
