### ISSUE TITLE
Add rvalue reference overloads to push-like functions in all Resource containers

### ISSUE THREAD

**Issue by avinabadasgupta** [sparcians/map#35]

**Comment by avinabadasgupta** [comment]
Continuation of work from #22 .

**Comment by klingaard** [comment]
Hey Avi, looks like the Queue change you made is not making gcc happy on Ubuntu.  Take a look at [latest failre](https://dev.azure.com/sparcians/map/_build/results?buildId=16&view=logs&j=1bf226d3-0e2f-52d8-fa93-7d9e633347b3&t=ec8d466d-e3b4-5115-4f06-222398f91e6c&l=883)

**Comment by klingaard** [comment]
@timsnyder , this is the change I was referring to

**Comment by avinabadasgupta** [comment]
Taking a look at it.

**Comment by klingaard** [comment]
There's a dependency on issue #53 for this to work almost everywhere.

**Comment by avinabadasgupta** [comment]
> There's a dependency on issue #53 for this to work almost everywhere.

Are most of the resources templated on SpartaSharedPointer?

**Comment by klingaard** [comment]
Yep
