### ISSUE TITLE
Setting parameters in `configureTree_()`

### ISSUE THREAD

**Issue by mhuzai** [sparcians/map#354]
I have a `Unit` that I would like to instantiate multiple times, each time attached to a different parent and with different parameters. I can instantiate the unit as I want in `buildTree_()`, but I can't seem to find any documentation on how to set the parameters of each instantiation in `configureTree_()`.

**Comment by klingaard** [comment]
Assuming you want to explicitly change parameters directly in your simulation (and not defining them via config files `-c` or `--arch`) you can find an example on slide 14 of the [Sparta Overivew](https://docs.google.com/presentation/d/e/2PACX-1vS1BWtVv0x3qXKQWAeECe2gsF9cMG3Zp2HnXJw52grCAcl21lv3a9pLW6J0lZ32e5DWdZkFyUMcE_AI/pub?start=false&loop=false&delayms=3000&slide=id.g7c850bbd55_1_118)

**Comment by mhuzai** [comment]
I could not find the function used on slide 14: `sparta::getParameters<T>()`. Has the API changed?

Instead, I got the following to work. If there's a better/cleaner way, please let me know!

```
auto* mc_rtn = getRoot()->getChildAs<sparta::ResourceTreeNode>("memory_controller");
auto& num_ports = mc_rtn->getParameterSet()->getParameterAs<uint32_t>("num_ports");
num_ports = 4;
```

**Comment by knute-sifive** [comment]
Ugh, you're right, the presentation is wrong.  I'll fix that.  Sorry 'bout that.

The code you have will work, but bypasses the `Parameter`'s validation mechanism as well as internal references.  That's ok if you're ok with that.  Suggested methodology (assuming your memory controller parameters are in a class called `MemoryControllerParams`):
```
auto* mc_rtn = getRoot()->getChildAs<sparta::ResourceTreeNode>("memory_controller");
auto& num_ports_params = mc_rtn->getChildAs<MemoryControllerParams>("params");
num_ports _params->num_ports = 4;
```
Please give this a try if you have a moment and let me know if this works.

**Comment by mhuzai** [comment]
Works like a charm, thank you!

Just required one minor change: `auto& num_ports_params` --> `auto* num_ports_params`.

**Comment by knute-sifive** [comment]
Perfect!  I updated my post.  Thank you!

**Comment by mhuzai** [comment]
One more question: Is there a way to share parameters between a node and its children, and propagate them from the node to the children? At the moment, I'm doing what you described above -- I go over the children of a node and override their parameters. But the issue with this is that these parameters show up in `params.yaml` even though setting them there has no effect because they are ultimately set within the program. Would using `HIDDEN_PARAMETER` for such parameters be the right solution? Or is there a cleaner way to do all this?

If it helps, the use case is, e.g., the user sets the number of PEs in an IP block, which then dictates the number of ports in the cache.

**Comment by mhuzai** [comment]
The factory idea worked great! Thank you!

I did not know of the existence of `onConfiguring()` and `onBuilding()` before seeing your example above. Are they not as well documented as `<build_|configure_|bind_>Tree` or did I miss something?

**Comment by klingaard** [comment]
﻿
It’s not well documented and on my list of stuff to do.   I’m thinking about moving it up on the list, however.

**Comment by knute-sifive** [comment]
I forgot to mention: there is an example of a custom factory in the CPU core model example: https://github.com/sparcians/map/blob/master/sparta/example/CoreModel/src/CPUFactory.cpp

**Comment by mhuzai** [comment]
Yes, that was a very useful reference!
