### ISSUE TITLE
Modeling a CAM

### ISSUE THREAD

**Issue by mhuzai** [sparcians/map#355]
Is there a plan to provide a container implementation to model content addressable memories? Or would that not really add anything on top of `std::unordered_map`?

**Comment by klingaard** [comment]
Are you looking to collect an `std:unordered_maps for pipeout?

Also, feel free to use the discussion forums for inquiries like these.   Good for documenting ideas/questions.

**Comment by knute-sifive** [comment]
Giving this more thought, I'm not sure exactly what you're asking.  "CAM'ing" over a structure like a data array looking for specific objects that satisfy a criteria (oldest ready instruction, for example), is usually brute force in a software model (iterating over entries).  But if you are "clever" and use the event approach, as the objects in the array meet the criteria, they are placed in an artificial, ordered "ready queue" off to the side.  At that point all you need to do is check that queue and pop off the bottom most entry.

**Comment by mhuzai** [comment]
My use case is an MSHR indexed by block address. Using `sparta::Buffer` and iterating over the entries was my initial approach. But I figured `std::unordered_map` would be much faster. I don't need a pipeout right now, but it would be certainly be useful in the future.

Thanks for pointing out the discussion forum. I hadn't noticed it earlier.
