### ISSUE TITLE
Confusing comments regarding state of SyncPort readiness (SyncPort::isReady())

### ISSUE THREAD

**Issue by alexanderFell** [sparcians/map#356]
In https://github.com/sparcians/map/blob/afacf1299e451578a7e242c77461995e6af1f02a/sparta/sparta/ports/SyncPort.hpp#L175 the method `isReady` allows specifying an offset from the current clock cycle to check the readiness of the port in the future and the comment for this parameter states: "Number of cycles the sender would use in a send() call when sending." According to the comment, this would be valid:

```
if(syncOutPort->isReady(10)) {
   syncOutPort->send(dataPacket, 10);
}
```

Since we do not know, what the future brings (in fact the bounded incoming port could have `setReady(false)` in the meantime). In case, the port is not ready by the time of sending (here in 10 clock cycles), the packet is recirculated.

However, `isReady` calls `_couldAccept()`.
The problem arises, that _couldAccept asserts that the parameter of `isReady` is 0 in https://github.com/sparcians/map/blob/afacf1299e451578a7e242c77461995e6af1f02a/sparta/sparta/ports/SyncPort.hpp#L768

This contradicts the comment regarding `isReady` and `couldAccept_` in https://github.com/sparcians/map/blob/master/sparta/sparta/ports/SyncPort.hpp#L34-L36: "When trying to send new data, SyncOutPort will then call SyncInPort::couldAccept_() to determine if data could be delivered on the given cycle."

As far as I can see, only `isReady` contains calls to `couldAccept_` but not the `send` method.

I must have misunderstood something. As of now, the code and the comments are contradictory and would appreciate a clarification.

**Comment by knute-sifive** [comment]
I see your quandary and there's definitely a possible contradiction between the default param value and the concept of next ready.  Need to chew on this one for a day and look at the SyncPort test.

**Comment by knute-sifive** [comment]
Ok, I've re-familiarized myself with this code (I wasn't the original author) and I think the SyncPort API was written to address two types of use cases (IIRC): 

1. Fire and forget allowing the SyncPort to send data on alignment between the clocks (via `forwardData_`)
2. A query API to allow the user to figure out when the data can be sent

I agree that the `isReady`'s default value is ... pointless.   

If you want to change/fix/remove the default value (and the docs), I'd be happy to take the PR.  Thanks for pointing it out.

**Comment by alexanderFell** [comment]
I just would like to clarify the purpose of `isReady`. It is like the comment says and I can determine, if there are already packets in flight, does the `isReady` report the current state of the connected input port or both? I am running experiments and the results are somehow a mix of the 3. For the following example I consider that if the port is not ready at the time of the scheduled send, automatically the packet will be sent, whenever the port becomes ready plus 1 clock (https://sparcians.github.io/map/SyncPort_8hpp.html)

According to this, I am using the following sequence in my simulator:

```
std::vector<std::unique_ptr<sparta::SyncOutPort<std::shared_ptr<CacheRequest>>>> outPorts;
controllerCycleEvent = std::make_unique<sparta::UniqueEvent<sparta::SchedulingPhase::Tick>>(
    &unit_event_set_, "controller_cycle", CREATE_SPARTA_HANDLER(Arbiter2, controllerCycle), 1
);

// init of ports, etc...

controllerCycle() {
   std::shared_ptr<CacheRequest> req = inPortsBuffer[in].front();
   if(outPorts[out]->isReady()) { // if port is becoming not ready, it will be effective next clock cycle
      DEBUG_MSG("READY");
      outPorts[out]->send(req, 1, true); // the allow_slide does not have any impact, assuming that its meaning is to accept packets and transmit them at N+1, when the input port becomes ready at N
      inPortsBuffer[in].pop();
   } else {
      DEBUG_MSG("NOT READY!");
   }
}
```
The receiving side:
```
sparta::SyncInPort<std::shared_ptr<CacheRequest>> in_port_mcpu_{&unit_port_set_, "in_mcpu", getClock()};
in_port_mcpu_.registerConsumerHandler(CREATE_SPARTA_HANDLER_WITH_DATA(MemoryController, receiveMessage_, std::shared_ptr<CacheRequest>));
sched = sparta::UniqueEvent<sparta::SchedulingPhase::Update>(&unit_event_set_, "controller", CREATE_SPARTA_HANDLER(MemoryController, controllerCycle), 1);

receiveMessage_(const std::shared_ptr<CacheRequest> &mes) {
   inFIFO.push(mes);
   sched.schedule(1);
}

controllerCycle() {
   in_port_mcpu_.setReady(inFIFO.size() < maxLimit);
   //....
}
```

Here is what I observe:

```
5d6: top.arch.memory_controller0.ports.in_mcpu: setting ready to: 1; num_in_flight = 0
5d6: READY
5d6: top.arch.memory_cpu0.crossbar.ports.out_arbiter1: SEND @5d7 allow_slide=1 # 0x55ceadeda630
5d6: top.arch.memory_controller0.ports.in_mcpu: RECEIVE SCHEDULED @5d7(0)  # 0x55ceadeda630
5d7: top.arch.memory_controller0.ports.in_mcpu: setting ready to: 1; num_in_flight = 1

// no data is sent to the port in 5d8, but the data is consumed by the inport, causing the buffer to be fully occupied

5d8: top.arch.memory_controller0.ports.in_mcpu: setting ready to: 0; num_in_flight = 0
5d8: READY
5d8: top.arch.memory_cpu0.crossbar.ports.out_arbiter1: SEND @5d9 allow_slide=1 # 0x55ceadedbe50
5d8: top.arch.memory_controller0.ports.in_mcpu: RECEIVE SCHEDULED @5d9(0)  # 0x55ceadedbe50
5d9: top.arch.memory_controller0.ports.in_mcpu: setting ready to: 1; num_in_flight = 1
5d9: top.arch.memory_controller0.ports.in_mcpu: RECEIVE SCHEDULED @5d9(0)  # 0x55ceadedbe50
terminate called after throwing an instance of 'sparta::SpartaException'
  what():  prev_data_arrival_tick_ < abs_scheduled_tick || prev_data_arrival_tick_ == PREV_DATA_ARRIVAL_TICK_INIT: top.arch.memory_controller0.ports.in_mcpu: attempt to schedule send for tick 1497, which is not later than the previous data at tick 1497; SyncInPorts should only get data once per cycle; data was: 0x55ceadedbe50: in file: '../map/sparta/sparta/ports/SyncPort.hpp', on line: 925
```

There is no problem that `isReady` reports true in `5d8`, although the readiness of the port has been set to false in the update phase. The documentation says that the readiness becomes in effect in the next clock cycle. Hence, in `5d8`, the output port will be allowed to send 1 more packet.

However, in `5d9` the input port becomes ready again. In this case, it is expected that, the current packet in flight (`0x55ceadedbe50`) will be delivered in `5da` (N+1). Also in `5da`, the ready signal is also recognized to be true again by the output port. Instead, I run into the mentioned assertion, since the sending cycle is the same as the arriving cycle (`5d9`)

I think my confusion originated in the purpose of the `isReady`, but it is spreading to other areas. Hence, I would appreciate if I could be given pointers about, how I shall address the problem. In addition, what is the meaning of the `allow_slide` if is it unrelated to the recirculation of packets. In this example, the behavior is identical if `allow_slide = false`. Regarding `allow_slide` the doc says "Allows the receive to slide relative to previous requests" which I think not really enlightening :)

**Comment by knute-sifive** [comment]
> I am running experiments and the results are somehow a mix of the 3. 

Ugh, I see.  Thank you for the detailed notes (I'm still parsing them).

I'd like to reproduce your experiment with a small test bench I have for SyncPorts.  It's probably not relevant, but can you tell me the clock ratio you're using?

**Comment by alexanderFell** [comment]
This is the clock:

Clocks (After Finalization):
_SPARTA_global_node_ : <_SPARTA_global_node_> {builtin} (privacy: 0)
+-clocks : <clocks (root)> (privacy: 0)
| +-Root : <Clock Root period=1> (privacy: 0)

**Comment by alexanderFell** [comment]
Thinking about it further. I think, there are 2 parts to the issue here: Incorrect documentation of the `isReady` method and an administrative issue in the recirculation.

Part 1: The purpose of `isReady` is to check, if the port can be used in the current clock cycle only. That is, is the input port ready to receive new data because it is ready (`setReady(true)`) AND there is no packet in flight. The `isReady` parameter can be omitted. Hence, the documentation in the details description describes it best (https://sparcians.github.io/map/SyncPort_8hpp.html).

Part 2: Since the `isReady` becomes false in the next clock cycle, if `setReady(false)` is called in this clock cycle, the output port can still submit 1 packet (assuming that there is none in flight already). Hence, the following if condition will be executed, even if `setReady(false)` is called in the same clock cycle (t).

```
inPort->setReady(false);
if(outPort->isReady()) {
   outPort->send(message, 1);
}
```
I am unsure, how the recirculation is implemented. Ideally, at t+1, the readiness of the input port is checked. If it is false, "park" the data and reschedule it until `setReady(true)` is called. Alternatively, schedule the packet for retransmission in every clock cycle. Looking at https://github.com/sparcians/map/blob/777d1566b8040d3ed816eeaa9078e89e231c7617/sparta/sparta/ports/SyncPort.hpp#L656 it seems the latter one is implemented.

I solved the assertion by replacing `send_(dat, receiver_clock_, sparta::Clock::Cycle(0), allow_slide, is_fwd_progress);` with `send_(dat, receiver_clock_, sparta::Clock::Cycle(1), allow_slide, is_fwd_progress);` (note the 1) For me, it shows the correct behavior now, but I have not tested corner cases.

Therefore, I suggest that I submit a PR (probably not today, but tomorrow). Then we can discuss the changes further, and you can try your test cases, if they still complete successfully.
Another PR would then be one that corrects the meaning of `isReady()`.

**Comment by knute-sifive** [comment]
I really appreciate your diving into this.  I have been underwater at work, so focus on this will have to wait for the weekend.  I do grok your intentions, however, and look forward to learning more about this myself.

**Comment by knute-sifive** [comment]
I believe this is resolved.  Alex, feel free to reopen if you think this still needs addressing.
