### ISSUE TITLE
Port Identification

### ISSUE THREAD

**Issue by mhuzai** [sparcians/map#357]
What is the preferred way to identify ports when multiple input ports have the same consumer handler? I currently use `CREATE_SPARTA_HANDLER_WITH_TWO_DATA` and pass in the port ID as the second parameter.

**Comment by knute-sifive** [comment]
I added `CREATE_SPARTA_HANDLER_WITH_TWO_DATA` for this exact use case.  😄 

The preferred way is to create separate handlers -- nice and clear.  But another way you can do this -- create a small structure that contains two parts:
1. A port ID
2. The data being sent

But, it's up to you.

**Comment by mhuzai** [comment]
Sounds good, thank you!

**Comment by rahul-neubla** [comment]
@mhuzai With `CREATE_SPARTA_HANDLER_WITH_TWO_DATA` how did u pass 2nd argument? The port has only one type of data. Which place did you send 2nd argument?
