### ISSUE TITLE
sparta::Vertex::unlink() uses iterator after std::List::erase()

### ISSUE THREAD

**Issue by timsnyder** [sparcians/map#36]
When I build for Linux using the conda toolchain, I hit a segfault in DAG_test as mentioned in https://github.com/sparcians/map/pull/34#issuecomment-596151410

```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000510053 in sparta::Vertex::unlink (this=0x1d821f0, efact=..., w=0x1d81820)
    at /home/conda/feedstock_root/build_artifacts/map_1583622171682/work/sparta/src/Vertex.cpp:50
50	                if (*el == ei->first) {
(gdb) p el
$1 = {_M_node = 0x10ec8348e5894855}
(gdb) p ei
$2 = {_M_node = 0x1d82810}
(gdb) p ei->first
$3 = (sparta::Vertex * const) 0x1d81820
(gdb) p *el
$4 = (sparta::Vertex *&) <error reading variable>
(gdb) list
45	        if (ei == outbound_edge_map_.end()) {
46	            // Edge not present -- just ignore
47	            return false;
48	        } else {
49	            for (auto el = outbound_edge_list_.begin(); el != outbound_edge_list_.end(); ++el) {
50	                if (*el == ei->first) {
51	                    outbound_edge_list_.erase(el);
52	                }
53	            }
54	            outbound_edge_map_.erase(ei);
(gdb) p (*el == ei->first)
Cannot access memory at address 0x10ec8348e5894865
```
Iterators passed to `std::List::erase()` are invalidated and `std::List::erase()` returns an iterator to the item following the one that was erased.  So, you can't let the for-loop increment the iterator because it will try to increment an invalid iterator after the erasure.

I'll be submitting a PR for this shortly.

**Comment by timsnyder** [comment]
I'm surprised that this doesn't fail all the time on other builds.

**Comment by timsnyder** [comment]
Rather than creating another PR for just this, I'm going to lump it into the PR #34 so that I can easily confirm that it fixes the failing test.

**Comment by klingaard** [comment]
Wow!  I can't believe this has been missed too!  That's programming 101 for iterators.  Thanks for catching and fixing.
