### ISSUE TITLE
Visualizing the DAG

### ISSUE THREAD

**Issue by mhuzai** [sparcians/map#361]
Is it possible to visualize the DAG generated by `--show-dag`? I couldn't find anything in the documentation, and I'm not familiar with the format used in the dump.

**Comment by knute-sifive** [comment]
Been meaning to add support to print a _clean_ DAG to a graphviz DOT file, but haven't had the time (low priority). If you're experiencing a DAG cycle issue, a `*.dot` file should have been generated in the run directory.  You can look at that file by using the `dot` tool from the `graphviz` library:

```
dot -Tpng cycle_detection.dot > cycle_detection.png
```

I think there are fancier tools that can visualize the DOT file, but I'm not as familiar with them.

**Comment by mhuzai** [comment]
Gotcha. I'm not experiencing a DAG cycle. I just wanted to see the final topology, but it's not super important.

Thank you!
