### ISSUE TITLE
To use this option COMPILE_WITH_PYTHON will causes failure

### ISSUE THREAD

**Issue by cyberspicecai** [sparcians/map#374]
Hi, authors
    I will try Python support in sparta, and find the building will fail. Sure, I will complete the building if remove the option.
    How to reprodue:
    1, OS ubuntu 20.04 LTS.
    2, in the dir map/sparta/release:
        cmake .. -DCMAKE_BUILD_TYPE=Release 
        this build cmdline is ok.  To verify the env.
    3, change the cmdline to 
           cmake .. -DCMAKE_BUILD_TYPE=Release -DCOMPILE_WITH_PYTHON=ON：
        the Error will:
[100%] Building CXX object CMakeFiles/sparta.dir/python/sparta_support/Completer.cpp.o
In file included from /usr/include/boost/bind.hpp:30,
                 from /home/caiyl/map_for_new_upstream/map_update_10_3/sparta/python/sparta_support/PythonInterpreter.cpp:11:
/usr/include/boost/bind.hpp:36:1: note: ‘#pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.’
   36 | BOOST_PRAGMA_MESSAGE(
      | ^~~~~~~~~~~~~~~~~~~~
/usr/include/boost/detail/iterator.hpp:13:1: note: ‘#pragma message: This header is deprecated. Use <iterator> instead.’
   13 | BOOST_HEADER_DEPRECATED("<iterator>")
      | ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/boost/smart_ptr/detail/sp_thread_sleep.hpp:22,
                 from /usr/include/boost/smart_ptr/detail/yield_k.hpp:23,
                 from /usr/include/boost/smart_ptr/detail/spinlock_gcc_atomic.hpp:14,
                 from /usr/include/boost/smart_ptr/detail/spinlock.hpp:42,
                 from /usr/include/boost/smart_ptr/detail/spinlock_pool.hpp:25,
                 from /usr/include/boost/smart_ptr/shared_ptr.hpp:29,
                 from /usr/include/boost/shared_ptr.hpp:17,
                 from /usr/include/boost/python/converter/shared_ptr_to_python.hpp:12,
                 from /usr/include/boost/python/converter/arg_to_python.hpp:15,
                 from /usr/include/boost/python/call.hpp:15,
                 from /usr/include/boost/python/object_core.hpp:14,
                 from /usr/include/boost/python/args.hpp:22,
                 from /usr/include/boost/python.hpp:11,
                 from /home/caiyl/map_for_new_upstream/map_update_10_3/sparta/./python/sparta_support/TreePathCompleter.hpp:22,
                 from /home/caiyl/map_for_new_upstream/map_update_10_3/sparta/python/sparta_support/Completer.cpp:5:
/usr/include/boost/bind.hpp:36:1: note: ‘#pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.’
   36 | BOOST_PRAGMA_MESSAGE(
      | ^~~~~~~~~~~~~~~~~~~~
/usr/include/boost/detail/iterator.hpp:13:1: note: ‘#pragma message: This header is deprecated. Use <iterator> instead.’
   13 | BOOST_HEADER_DEPRECATED("<iterator>")
      | ^~~~~~~~~~~~~~~~~~~~~~~
[100%] Built target simdb
In file included from /usr/include/boost/smart_ptr/detail/sp_thread_sleep.hpp:22,
                 from /usr/include/boost/smart_ptr/detail/yield_k.hpp:23,
                 from /usr/include/boost/smart_ptr/detail/spinlock_gcc_atomic.hpp:14,
                 from /usr/include/boost/smart_ptr/detail/spinlock.hpp:42,
                 from /usr/include/boost/smart_ptr/detail/spinlock_pool.hpp:25,
                 from /usr/include/boost/smart_ptr/shared_ptr.hpp:29,
                 from /usr/include/boost/shared_ptr.hpp:17,
                 from /usr/include/boost/python/converter/shared_ptr_to_python.hpp:12,
                 from /usr/include/boost/python/converter/arg_to_python.hpp:15,
                 from /usr/include/boost/python/call.hpp:15,
                 from /usr/include/boost/python/object_core.hpp:14,
                 from /usr/include/boost/python/args.hpp:22,
                 from /usr/include/boost/python.hpp:11,
                 from /home/caiyl/map_for_new_upstream/map_update_10_3/sparta/./python/sparta_support/TreePathCompleter.hpp:22,
                 from /home/caiyl/map_for_new_upstream/map_update_10_3/sparta/python/sparta_support/module_sparta.cpp:30:
/usr/include/boost/bind.hpp:36:1: note: ‘#pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.’
   36 | BOOST_PRAGMA_MESSAGE(
      | ^~~~~~~~~~~~~~~~~~~~
/usr/include/boost/detail/iterator.hpp:13:1: note: ‘#pragma message: This header is deprecated. Use <iterator> instead.’
   13 | BOOST_HEADER_DEPRECATED("<iterator>")
      | ^~~~~~~~~~~~~~~~~~~~~~~
/home/caiyl/map_for_new_upstream/map_update_10_3/sparta/python/sparta_support/module_sparta.cpp: In function ‘void LOCAL_SimulationDatabase__printVerifFailureSummary(const simdb::ObjectManager&, simdb::DatabaseID, simdb::DatabaseID)’:
/home/caiyl/map_for_new_upstream/map_update_10_3/sparta/python/sparta_support/module_sparta.cpp:1246:38: error: variable ‘simdb::ObjectQuery summary_query’ has initializer but incomplete type
 1246 |     simdb::ObjectQuery summary_query(sim_db, "ReportVerificationFailureSummaries");
      |                                      ^~~~~~
/home/caiyl/map_for_new_upstream/map_update_10_3/sparta/python/sparta_support/module_sparta.cpp:1259:39: error: variable ‘simdb::ObjectQuery sim_info_query’ has initializer but incomplete type
 1259 |     simdb::ObjectQuery sim_info_query(sim_db, "SimInfo");
      |                                       ^~~~~~
/home/caiyl/map_for_new_upstream/map_update_10_3/sparta/python/sparta_support/module_sparta.cpp: In lambda function:
/home/caiyl/map_for_new_upstream/map_update_10_3/sparta/python/sparta_support/module_sparta.cpp:1324:44: error: variable ‘simdb::ObjectQuery passed_query’ has initializer but incomplete type
 1324 |             simdb::ObjectQuery passed_query(*sim_db, "ReportVerificationResults");
      |                                            ^
/home/caiyl/map_for_new_upstream/map_update_10_3/sparta/python/sparta_support/module_sparta.cpp:1371:40: error: variable ‘simdb::ObjectQuery failed_query’ has initializer but incomplete type
 1371 |         simdb::ObjectQuery failed_query(*sim_db, "ReportVerificationResults");
      |                                        ^
/home/caiyl/map_for_new_upstream/map_update_10_3/sparta/python/sparta_support/module_sparta.cpp: In lambda function:
/home/caiyl/map_for_new_upstream/map_update_10_3/sparta/python/sparta_support/module_sparta.cpp:1482:33: error: variable ‘simdb::ObjectQuery query’ has initializer but incomplete type
 1482 |         simdb::ObjectQuery query(*sim_db, "ReportVerificationDeepCopyFiles");
      |                                 ^
/home/caiyl/map_for_new_upstream/map_update_10_3/sparta/python/sparta_support/module_sparta.cpp: In function ‘void SimulationDatabase__getVerificationFailuresInDir(const string&)’:
/home/caiyl/map_for_new_upstream/map_update_10_3/sparta/python/sparta_support/module_sparta.cpp:1536:43: error: variable ‘simdb::ObjectQuery query’ has initializer but incomplete type
 1536 |                  simdb::ObjectQuery query(sim_db, "ReportVerificationDeepCopyFiles");
      |                                           ^~~~~~
make[2]: *** [CMakeFiles/sparta.dir/build.make:972: CMakeFiles/sparta.dir/python/sparta_support/module_sparta.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:1949: CMakeFiles/sparta.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

pls help to debug.
Thanks a lot.
Cyberspice.

**Comment by klingaard** [comment]
I think this is related to newer compilers cracking down on the rule of 3 (or 5 for c++11).  What version of the compiler are you using?

**Comment by klingaard** [comment]
This is also related to issue #367

**Comment by cyberspicecai** [comment]
> I think this is related to newer compilers cracking down on the rule of 3 (or 5 for c++11). What version of the compiler are you using?
 that' great, Knute, I check the compiling with gcc 9.4 version and finish the building. My former gcc version is 11.2.0. 
And would you pls help debug this issue ?

**Comment by knute-sifive** [comment]
See if branch knutel/issue_367_pedantic_fixes, PR #375 fixes your issue.

**Comment by cyberspicecai** [comment]
Hi Knute,
    I think the branch of "knutel/issue_367_pedantic_fixes" compiles sparta infa ok.

     But in compiling example and test dirs, the time is long and the issue pops again:
/usr/bin/ld: [ 95%] Linking CXX executable Events_example_test
/usr/bin/ld: [ 97%] Linking CXX executable Ports_example_test
/usr/bin/ld: [100%] Linking CXX executable sparta_skeleton
/usr/bin/ld:


[100%] Linking CXX executable sparta_core_example
/usr/bin/ld: [100%] Linking CXX executable dynamic_model_pipeline
/usr/bin/ld:



../../../libsparta.a(module_sparta.cpp.o):(.bss+0x120): multiple definition of `sparta::facade::indent'; ../../../libsparta.a(module_sparta.cpp.o):(.bss+0x120): multiple definition of `sparta::facade::indent'; ../../../libsparta.a(module_sparta.cpp.o):(.bss+0x120): multiple definition of `sparta::facade::indent'; ../../libsparta.a(module_sparta.cpp.o):(.bss+0x120): multiple definition of `sparta::facade::indent'; ../../../libsparta.a(ReportDescriptor.cpp.o):(.bss+0x0): first defined here
/usr/bin/ld: ../../../libsparta.a(PythonInterpreter.cpp.o):(.bss+0x8): multiple definition of `sparta::facade::indent'; ../../../libsparta.a(ReportDescriptor.cpp.o):(.bss+0x0): first defined here
/usr/bin/ld: ../../libsparta.a(module_sparta.cpp.o):(.bss+0x120): multiple definition of `sparta::facade::indent'; ../../../libsparta.a(Completer.cpp.o):(.bss+0x0): multiple definition of `sparta::facade::indent'; ../../../libsparta.a(ReportDescriptor.cpp.o):(.bss+0x0): first defined here

**Comment by cyberspicecai** [comment]
great,Knute, I check your new branch, it works.  Thanks a lot .

**Comment by cyberspicecai** [comment]
thanks for Knute's quick response. The issue is resolved.
