### ISSUE TITLE
Extensions referenced in code not dumped in final config

### ISSUE THREAD

**Issue by knute-sifive** [sparcians/map#440]
If an extension were referred to in the simulator source base like this:
```
        auto extension = getRoot()->getExtension("simulation_configuration");
```
but NEVER referred to in a YAML file supplied by `-c <yaml>` or `--arch <config>` nor given via the `-p extension <value>` option, the final config will not contain the extension.

I.e. this fails to write any extensions:
```
my_sim --write-final-config config --no-run
```

**Comment by knute-sifive** [comment]
CC: @davidsifive

**Comment by furuame** [comment]
😲
