### ISSUE TITLE
Expose scheduler event as a counter

### ISSUE THREAD

**Issue by MichaelSchoenfelder-SiV** [sparcians/map#448]
As a DevOps person, I want to monitor the efficiency of the simulators themselves.  Key simulator performance metrics are "Events per Instruction", "kilo-events per second" and "kilo-instructions per second".  "Instructions" are concept of a CPU core performance model, so the simulator is responsible for that metric.  Sparta already has time counters, so all I am missing is "events".

Request: Please add a counter for events, so I can use the Sparta reporting subsystem to write reports on simulator performance.

**Comment by knute-sifive** [comment]
New counter in Scheduler added: `scheduler.events_fired`

PR coming soon.
