### ISSUE TITLE
Conditionally compile Collectable::collect on ostream operator availability 

### ISSUE THREAD

**Issue by avinabadasgupta** [sparcians/map#45]
Most of the resource classes have internal iterable collectors which enable them for pipeline collection.
Currently, there is a strict restriction that the template type of resources must know how to respond to ostream operators.
This is cumbersome for cases where we need resources but do not care about pipeline collection.
We should not compile Collectable code that needs ostream operators if ostream operators are not defined by the template type.
This can be easily achieved with a mixture of constexpr if statement with has_ostream_operator metafunction in Utils.h.

**Comment by klingaard** [comment]
@cnyce will be addressing this with a new SimDB.
