### ISSUE TITLE
PriorityQueue tries to initialize Datatype

### ISSUE THREAD

**Issue by h0lyalg0rithm** [sparcians/map#452]
I am trying to use the new priority queue with an object whose constructor is marked as deleted.
Is there way to work around this, looking at the code I didnt see any other way than allowing default constructor calls on the object 
Link to [class](https://github.com/riscv-software-src/riscv-perf-model/blob/82504f6f68374d4b335d9de3d5d3890fe55e9838/core/LSU.hpp#L118)

@knute-sifive @klingaard

**Comment by knute-sifive** [comment]
You should not be using concrete objects in the PQ.  Instead, you should use SpartaSharedPointers instead.  Making copies of the original LoadStoreInfo objects is not efficient and you don't want to send a _copy_ of the LSI down the pipe, right?
