### ISSUE TITLE
Release pipeViewer

### ISSUE THREAD

**Issue by timsnyder** [sparcians/map#50]
Get the pipeViewer working on Linux and checked into sparcians/map

**Comment by timsnyder** [comment]
I've limited the scope of this first ticket to Linux because there is some work that will need to be done for macOS.  In short, the wxpython package needs to be tweaked a bit.  I'm working on that on the side in https://github.com/conda-forge/wxpython-feedstock/issues/28

**Comment by timsnyder** [comment]
My fixes to the conda-forge wxpython package that make it include the wxWidgets library headers and `wx-config` helper utility have been merged https://github.com/conda-forge/wxpython-feedstock/pull/46 and are now available with `conda install -c conda-forge wxpython`.

I'm going to push to get my Argos PR opened today.

**Comment by klingaard** [comment]
That's awesome.  Thanks, Tim!
