### ISSUE TITLE
the filename State.tpp isn't correct

### ISSUE THREAD

**Issue by FlashBarryAllen** [sparcians/map#505]
`map/sparta/src/State.tpp` isn't correct.  change it to `State.cpp`.

**Comment by klingaard** [comment]
The contents of that file are template implementations and thus isn't a directly compile-able file.  There are neither listed template specializations nor template instances.   The file is actually included by Simulation.cpp

The naming convention is common, actually.  A quick reference of discussion: https://stackoverflow.com/questions/29264656/c-template-implementation-file-extension-convention
