### ISSUE TITLE
New move operations in SpartaSharedPointer tanks performance

### ISSUE THREAD

**Issue by klingaard** [sparcians/map#59]
I thought I was being clever in the move operations of SpartaSharedPointer by setting the orig's internal refcounter object to a new one -- but this adds unnecessary allocations!  Need to rethink SpartaSharedPointer a bit...

**Comment by klingaard** [comment]
Ok, so I've taken Avi's advice and just nullified the internal `ref_count_` on a dead SpartaSharedPointer (specifically one that's been moved _from_).  I added assertions to ensure you're not working with a dead SpartaSharedPointer and updated the test.

**Comment by avinabadasgupta** [comment]
How much is the tester clocking now?

**Comment by klingaard** [comment]
MUCH better -- back to what it was.
