### ISSUE TITLE
It'd be handy to allow use of `const` methods for CREATE_SPARTA_HANDLER

### ISSUE THREAD

**Issue by klingaard** [sparcians/map#68]
Now, I'd love to abandon the macro completely and just use some cool C++17 feature, but for now it'd be handy to be able to create a SpartaHandler with a const method:

```
class Foo
{
private:
    void myMethod_() const {}
};

Foo::Foo()
{
    auto func = CREATE_SPARTA_HANDLER(Foo, myMethod_);
}
```
You get this when you try this:
```
error: no matching function for call to 'from_member'
             CREATE_SPARTA_HANDLER(Foo, myMethod_)};
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 note: expanded from macro 'CREATE_SPARTA_HANDLER'
    sparta::SpartaHandler::from_member<clname, &clname::meth>            \
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 note: candidate template ignored: invalid explicitly-specified argument for template parameter 'TMethod'
        static SpartaHandler from_member(T* object_ptr, const char * name = "")
```

**Comment by klingaard** [comment]
Background task for you, Avi.  This one would be kind of fun to tackle.

**Comment by avinabadasgupta** [comment]
Which one?
Adding const methods to SpartaHandler or removing the macro completely?

**Comment by avinabadasgupta** [comment]
To add the const methods, shouldn't it just be this variation
```
#define CREATE_SPARTA_HANDLER(clname, meth)                                    \
    sparta::SpartaHandler::from_member<clname, &clname::meth>            \
    (this, #clname"::"#meth"()")
```
to
```
#define CREATE_SPARTA_HANDLER_CONST(clname, meth)                       \
    sparta::SpartaHandler::from_member<clname, &clname::meth>             \
    (this, #clname"::"#meth"() const")
```

**Comment by klingaard** [comment]
I dunno.  :)  Maybe...  Getting rid of the macros would be the next challenge!

Basically, change this:
```
a_delay_in_.registerConsumerHandler
    (CREATE_SPARTA_HANDLER_WITH_DATA(MyDevice, myDataReceiver_, uint32_t));
```
to this:
```
a_delay_in_.registerConsumerHandler(myDataReceiver_);
```

BTW, did you know that you can cast a SpartaHandler to an `std::function`?  I accidentally did this the other day and it works!

**Comment by avinabadasgupta** [comment]
> I dunno. :) Maybe... Getting rid of the macros would be the next challenge!
> 
> Basically, change this:
> 
> ```
> a_delay_in_.registerConsumerHandler
>     (CREATE_SPARTA_HANDLER_WITH_DATA(MyDevice, myDataReceiver_, uint32_t));
> ```
> 
> to this:
> 
> ```
> a_delay_in_.registerConsumerHandler(myDataReceiver_);
> ```
> 
> BTW, did you know that you can cast a SpartaHandler to an `std::function`? I accidentally did this the other day and it works!

Never even thought about it!

**Comment by avinabadasgupta** [comment]
> I dunno. :) Maybe... Getting rid of the macros would be the next challenge!
> 
> Basically, change this:
> 
> ```
> a_delay_in_.registerConsumerHandler
>     (CREATE_SPARTA_HANDLER_WITH_DATA(MyDevice, myDataReceiver_, uint32_t));
> ```
> 
> to this:
> 
> ```
> a_delay_in_.registerConsumerHandler(myDataReceiver_);
> ```
> 
> BTW, did you know that you can cast a SpartaHandler to an `std::function`? I accidentally did this the other day and it works!

I'm thinking about this.
I do not think
```
a_delay_in_.registerConsumerHandler(myDataReceiver_);
```
would work.
What could work is
```
a_delay_in_.registerConsumerHandler(this, myDataReceiver_);
```
Reason is, we need to store the object instance for the dispatch later on.
From ```myDataReceiver_```, we can figure everything out, which class it belongs to, what are the number and type its parameters, but cannot get a hold of the object's instance.
