### ISSUE TITLE
Print resource name during port errors of disparate types

### ISSUE THREAD

**Issue by benoy-sifive** [sparcians/map#69]
Example:

`Error setting up simulator because of an exception:`
`ERROR: Attempt to bind DataInPort of a disparate types: 'in_data_read_req' to 'out_req'`

Would it be possible to add the resource names and/or the hierarchy of both when this error occurs?

**Comment by klingaard** [comment]
Changed `getName()` to `getLocation()` in the error messages.  Checked SyncPorts and it had the correct strings.
