### ISSUE TITLE
Simulator dies when '-h' or '--help' is specified on the command line

### ISSUE THREAD

**Issue by davidsifive** [sparcians/map#7]
My command line simulator dies with:

`libc++abi.dylib: terminating with uncaught exception of type sparta::SpartaException: Cannot setup simulation before parsing command line`

when ‘-h’ or ‘--help’ is specified on the command line. ‘--help-tree’ works fine. I little spelunking in CommandLineSimulator.cpp makes be believe that ‘-h’ or ‘--help’ should set no_run_mode_, but it does not.

**Comment by klingaard** [comment]
So I can't reproduce this on the simulators that are in the examples directory nor in the Sparta testers.  However, I can see this issue with other testers I've created.  I'll look into it.

**Comment by klingaard** [comment]
Ok, so the issue in the other testers I was looking at was the error code from `CommandLineSimulator::parse` was being ignored.  It's returning `false` and the simulator writer shouldn't ignore that -- they should stop simulation on their own.

This doesn't mean Sparta isn't being clear on the issue, however.  I can clean up the code a bit to indicate that parsing the command wasn't done OR an error was detected during command line parsing and is being ignored.  I'll do that.

**Comment by klingaard** [comment]
BTW, the error_code in this case is still 0.  There isn't an error on printing -h options, from our humble opinion.  Either way, the parse function does return false.
