### ISSUE TITLE
I'd be handy if `State` was copy constructible

### ISSUE THREAD

**Issue by klingaard** [sparcians/map#8]
Since the `State` class in `simulation` is used by dynamically created objects, it'd be handy to have this class copyable.

**Comment by avinabadasgupta** [comment]
@klingaard The reason I made State class non copyable is because every State class has a state tracking unit member which is a std::unique_ptr.

**Comment by klingaard** [comment]
Need to make it deep.  The use case comes from a user creating an instruction decoder that creates and caches instruction prototypes.   When the decoder has a hit in a decoder cache, the prototype is used to create a new instruction via the copy constructor.  The hope that this is faster than calling the Instruction's constructor every time an instruction object is created.  

The instruction object contains a State object.

**Comment by klingaard** [comment]
Hey Avi, how's it going with this?

**Comment by avinabadasgupta** [comment]
Running into some segfaults rooting from the scheduler. Investigating.
