### ISSUE TITLE
Include guards are not compliant

### ISSUE THREAD

**Issue by klingaard** [sparcians/map#83]
The include guards that Sparta uses are not compliant with the industry standard.  Specifically, they should not start with underscores.  

There are two solutions:

1. Use `#pragma once`
  There's a holy war regarding this on the net.  First, this is a _compile time_ directive and not a preprocessor one (possible slower compiles).  Secondly, if there are multiple files with the same name (different directories), you'll drop both automatically.  Now, in Sparta, I hope we don't have that kind of crappy design, so I'm not too worried about it.  Third, it's not standard, but most compilers (if not all) support it
1. Define a standard format
  If we keep the `#ifdef` guards, Sparta should adopt a standard.  I propose this: `SPARTA_<function>_<filename>_H` where `function` is `kernel`, `simulation`, `events`, etc.

I like the second one.  Thoughts?

**Comment by avinabadasgupta** [comment]
Why do we need to include the function name in the guard?

**Comment by klingaard** [comment]
Ah, let me clarify.  It's not the function name as in C++ function name, but the sparta function.  For example, one of these:
```
app
argos
async
collection
control
decode
dynamic_pipeline
events
functional
kernel
log
memory
pairs
parsers
pevents
ports
report
resources
serialization
simulation
sparta.hpp
statistics
tree
trigger
utils
```

**Comment by avinabadasgupta** [comment]
I vote for ```#pragma once``` because there is a performance benefit of not having to reopen a file once the ```#pragma once``` has been read. 
With guards, you need to reopen the files, read the symbol and check if that is already defined or not.

**Comment by klingaard** [comment]
Ok, I'll write a quick awk script and replace all header guards with the pragma.  I'll give it whirl!

**Comment by klingaard** [comment]
Ok, I pushed a first cut of this to `knute/issue_83_inc_guards`.  Seemed to work fine.  Even tested it with software at SiFive.  Compile times did _not_ increase and the binaries were the same.  However, everything's now consistent.
