### ISSUE TITLE
Fix QueueIterator copy assignment

### ISSUE THREAD

**Issue by TopChangwatchaiSiFive** [sparcians/map#84]
QueueIterator copy assignment is buggy.  In this code:

```
            QueueIterator& operator=(const QueueIterator& rhs)
            {
                attached_queue_ = rhs.attached_queue_;
                physical_idx_ = rhs.physical_idx_;
                unique_id_ = rhs.physical_idx_;
                return *this;
            }
```
the line should read:
```
                unique_id_ = rhs.unique_id_;
```

**Comment by avinabadasgupta** [comment]
oh wow, wonder how that even worked.

**Comment by TopChangwatchaiSiFive** [comment]
The doxygen comment for this method mentions something about `validator_`, but I don't know what this is referring to.  I notice there's something called `validator_` in Buffer...perhaps just a copy/paste error.

**Comment by avinabadasgupta** [comment]
I'll take a look and push a fix in some time.

**Comment by TopChangwatchaiSiFive** [comment]
Awesome, thanks.

**Comment by klingaard** [comment]
This is probably a good opportunity to remove the implementation and just `= default`

**Comment by TopChangwatchaiSiFive** [comment]
Should make it more maintainable.

May want to look at Pipeline.hpp as well.
