### ISSUE TITLE
Registers cannot be reset unless initial_value is specified

### ISSUE THREAD

**Issue by kathlenehurt-sifive** [sparcians/map#88]
If a Register is initialized without the initial_value specified, like in the following Register::Definition, the reset() method causes a segfault.
`sparta::Register::Definition reg_def = {  0, "reg0", 0, "group", 0, "register 0", 4, {}, {}, nullptr,  Register::INVALID_ID, 0, nullptr, 0, 0 }`

When initial_value is not specified, a default initial value is used:
`<top.dummy.regs.reg0 32 bits cc cc cc cc>`

When calling reset() in this scenario I would expect the register to be reset to the default initial value.

**Comment by klingaard** [comment]
I can reproduce the issue in the Register_test

**Comment by klingaard** [comment]
Fixed on branch knute/issue_88_reg_reset.  Waiting for other PRs to be merged before setting up this one.
