### ISSUE TITLE
Cannot write to a Field that is the same size as a Register

### ISSUE THREAD

**Issue by kathlenehurt-sifive** [sparcians/map#89]
It looks like the mask is computed incorrectly when writing to a Field that is the same size as a Register.

I have a 64 bit Register with 2 fields 'sp' and 'dp' where field sp is the lower 32 bits and field dp is the whole registers (64 bits). When I try to write to dp I get this error:
`libc++abi.dylib: terminating with uncaught exception of type sparta::SpartaException: (val & ~mask_) == utils::BitArray(access_type(0), reg_size_): Value of 1 too large for bit field top.dummy.regs.f0.dp of size 64`

Printing the Field also indicates that there is something wrong here:
`<top.dummy.regs.f0.sp [0-31] 32 bits LE:0xf0f0f0f0>`
`<top.dummy.regs.f0.dp [0-63] 64 bits LE:0x0>`

**Comment by klingaard** [comment]
That's weird.

**Comment by klingaard** [comment]
I'm able to reproduce this issue in the Register_test
