### ISSUE TITLE
CircularBuffer support for const_iterators

### ISSUE THREAD

**Issue by benoy-sifive** [sparcians/map#90]
Currently, there are no const_iterators begin(), end(), .etc. support other than "SPARTA_GCC_VERSION > 40800".
Can support for these for other compilers please be added?

**Comment by avinabadasgupta** [comment]
I believe we did that because we needed a C++11 compliant compiler to figure out the type of the iterator using a C++11 feature.

**Comment by klingaard** [comment]
Actually there was a bug in gcc that prevented this from compiling.  I thought this code was fixed, but apparently not.  We just need to get rid of the define and turn on some testing (I think the testers have the same `#define`)

**Comment by klingaard** [comment]
Hey Avi, do you want to fix this one or shall I?

**Comment by avinabadasgupta** [comment]
> Hey Avi, do you want to fix this one or shall I?

Please take this one.

**Comment by klingaard** [comment]
You got it!

**Comment by benoy-sifive** [comment]
Thanks for the speedy fix!
