### ISSUE TITLE
Add clang 10.0 to CI

### ISSUE THREAD

**Issue by timsnyder** [sparcians/map#95]
LLVM 10.0.0 was released a few weeks back and the conda packages are becoming available soon. The conda package PR for clang 10 is https://github.com/conda-forge/clangdev-feedstock/pull/83

@klingaard, if you're interested in trying clang-10, I can easily provide the oneline tweak to the CI setup to build both 9.0.1 and 10.0.0 once the PR above is merged.

**Comment by klingaard** [comment]
I am interested, but not today.  There's a lot of other fish I need to fry...

**Comment by timsnyder** [comment]
Ok.  I wasn't thinking you'd have to do anything.  I can just try to build it and give you an idea of whether it just builds cleanly, in which case, I'll add it to the CI, so that it stays clean. If it isn't clean, I'll just capture instructions on how you or anyone else can build with it to resolve the issues and add it to the CI once someone has time and interest that intersect. :)

**Comment by klingaard** [comment]
Oh, ok.  That sounds good.  Please proceed!

**Comment by jackjchen** [comment]
I happened to update (--all) my local macOS conda envirnoment with clang 10, and the build failed with some type conversion errors. I'll pin it to clang 9 or just use Apple native clang.

**Comment by timsnyder** [comment]
@jackjchen, to build locally on macOS, you need to also supply `-m .ci_support/osx_<one_of_several_options>.yaml` to `conda-build`.  The CI will use the pins specified in https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml so as to be consistent with what the conda-forge guys are using.

That being said, I also need to pin the duplicated clang requirement for the linux builds because they are a bit of a hack right now.

**Comment by timsnyder-siv** [comment]
Looks like they have up to clang 14 available now FYI.

**Comment by timsnyder-siv** [comment]
And we're currently running 10 and 11 in CI...

**Comment by klingaard** [comment]
Wonder how well Sparta holds up to clang 14.

**Comment by timsnyder** [comment]
Closed via #317
